#!/bin/bash
set -e
set -x

SNARKLIB_SRC=${SNARKLIB_SRC:-https://github.com/jancarlsson/snarklib.git}
CRYPTL_SRC=${CRYPTL_SRC:-https://github.com/jancarlsson/cryptl.git}
SNARKFRONT_SRC=${SNARKFRONT_SRC:-https://github.com/jancarlsson/snarkfront.git}

[ ! -d snarklib ] && git clone --recursive $SNARKLIB_SRC snarklib
cd snarklib/
make install PREFIX=/usr/local

cd ..
[ ! -d cryptl ] && git clone --recursive $CRYPTL_SRC cryptl
cd cryptl/
make install PREFIX=/usr/local

cd ..
[ ! -d snarkfront ] && git clone --recursive $SNARKFRONT_SRC snarkfront
cd snarkfront/
make archive tools tests PREFIX=/usr/local
make lib PREFIX=/usr/local
make install PREFIX=/usr/local
