package xjsnark.merkleTree;

/*Generated by MPS */

import backend.auxTypes.StructDefinition;
import backend.auxTypes.UnsignedInteger;
import java.math.BigInteger;
import backend.structure.CircuitGenerator;
import java.util.ArrayList;
import backend.auxTypes.VariableState;
import backend.auxTypes.IAuxType;

public class MerklePath extends StructDefinition {


  /*package*/ UnsignedInteger directionSelector = new UnsignedInteger(64, new BigInteger("0"));
  /*package*/ Node[] nodes = new Node[MerkleTree.HEIGHT];
  public MerklePath() {
    for (int i = 0; i < nodes.length; i++) {
      nodes[i] = new Node();
    }
  }


  public void __makeInput() {

    directionSelector = UnsignedInteger.createInput(CircuitGenerator.__getActiveCircuitGenerator(), 64);





    if (nodes != null) {
      for (int i = 0; i < nodes.length; i++) {
        if (nodes[i] != null) {
          nodes[i].__makeInput();
        }
      }

    }





  }


  public void __makeOutput() {
    UnsignedInteger.makeOutput(CircuitGenerator.__getActiveCircuitGenerator(), directionSelector);





    if (nodes != null) {
      for (int i = 0; i < nodes.length; i++) {
        if (nodes[i] != null) {
          nodes[i].__makeOutput();
        }
      }

    }
  }


  public void __makeWitness() {


    directionSelector = UnsignedInteger.createWitness(CircuitGenerator.__getActiveCircuitGenerator(), 64);





    if (nodes != null) {
      for (int i = 0; i < nodes.length; i++) {
        if (nodes[i] != null) {
          nodes[i].__makeWitness();
        }
      }

    }





  }


  public void __makeVerifiedWitness() {

    directionSelector = UnsignedInteger.createVerifiedWitness(CircuitGenerator.__getActiveCircuitGenerator(), 64);





    if (nodes != null) {
      for (int i = 0; i < nodes.length; i++) {
        if (nodes[i] != null) {
          nodes[i].__makeVerifiedWitness();
        }
      }

    }






  }

  public void __alignAndPackAll() {

    ArrayList<VariableState> states = new ArrayList();
    states.add(directionSelector.getState());





    if (nodes != null) {
      for (int i = 0; i < nodes.length; i++) {
        if (nodes[i] != null) {
          nodes[i].__alignAndPackAll();
        }
      }

    }


    for (VariableState state : states) {
      state.setPackedAhead(true);
      state.setMustBeWithinRange(true);
      state.setConditionallySplittedAndAlignedAhead(true);
    }

  }
  public static Class<?> __getClassRef() {
    return MerklePath.class;
  }

  public StructDefinition __copy() {
    return null;
  }
  public int[] __getBasicElementsDetails() {
    return null;
  }
  public ArrayList<IAuxType> __getBasicElements() {
    ArrayList<IAuxType> list = new ArrayList();
    list.add(directionSelector);





    if (nodes != null) {
      for (int i = 0; i < nodes.length; i++) {
        if (nodes[i] != null) {
          list.addAll(nodes[i].__getBasicElements());
        }
      }

    }


    return list;
  }
}
