package xjsnark.merkleTreeConstruction;

/*Generated by MPS */

import backend.auxTypes.StructDefinition;
import backend.auxTypes.UnsignedInteger;
import backend.structure.CircuitGenerator;
import java.util.ArrayList;
import backend.auxTypes.VariableState;
import backend.auxTypes.IAuxType;

public class Leaf extends StructDefinition {


  /*package*/ UnsignedInteger[] node = (UnsignedInteger[]) UnsignedInteger.createZeroArray(CircuitGenerator.__getActiveCircuitGenerator(), new int[]{16}, 32);


  public void __makeInput() {

    node = UnsignedInteger.createInputArray(CircuitGenerator.__getActiveCircuitGenerator(), node.length, 32);










  }


  public void __makeOutput() {
    UnsignedInteger.makeOutput(CircuitGenerator.__getActiveCircuitGenerator(), node);





  }


  public void __makeWitness() {


    node = UnsignedInteger.createWitnessArray(CircuitGenerator.__getActiveCircuitGenerator(), node.length, 32);










  }


  public void __makeVerifiedWitness() {

    node = UnsignedInteger.createVerifiedWitnessArray(CircuitGenerator.__getActiveCircuitGenerator(), node.length, 32);











  }

  public void __alignAndPackAll() {

    ArrayList<VariableState> states = new ArrayList();

    for (int i = 0; i < node.length; i++) {
      states.add(node[i].getState());
    }






    for (VariableState state : states) {
      state.setPackedAhead(true);
      state.setMustBeWithinRange(true);
      state.setConditionallySplittedAndAlignedAhead(true);
    }

  }
  public static Class<?> __getClassRef() {
    return Leaf.class;
  }

  public StructDefinition __copy() {
    return null;
  }
  public int[] __getBasicElementsDetails() {
    return null;
  }
  public ArrayList<IAuxType> __getBasicElements() {
    ArrayList<IAuxType> list = new ArrayList();

    for (int i = 0; i < node.length; i++) {
      list.add(node[i]);
    }






    return list;
  }
}
