#!/bin/bash
set -e
set -x

JSNARK_SRC=${JSNARK_SRC:-https://github.com/akosba/jsnark.git}
[ ! -d jsnark ] && git clone --recursive $JSNARK_SRC jsnark
cd jsnark/libsnark
./prepare-depends.sh
make
cd ..
cd JsnarkCircuitBuilder
mkdir -p bin
javac -d bin -cp /usr/share/java/junit4.jar  $(find ./src/* | grep ".java$")
